# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b540819e6c06e3989f14baf79feecda88c803e4c22a7f53b3ed89167713135df5c5cf001c063e486dc502251f415b4e7298ae3392af54d29a0f0fc1d3f17830e

test:
  secret_key_base: 449ac290fb0e4e08a5f962af6a81a199b3fe014dd4a330e2d8f9aef8067e9f7019c75f444c189dd76ae6e9ac961f978aa2e1b41e98229d368f9b29dfc2188362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
